# Generated by Django 5.2.11 on 2026-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_serviceprice_subservice_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verification_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
