# Generated by Django 5.2.11 on 2026-04-09 15:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_subservice_points_to_announcement_and_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPricing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("scale", "Scale"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("commission_rate__gte", 0), ("commission_rate__lte", 100)),
                        name="organization_pricing_commission_rate_between_0_and_100",
                    )
                ],
            },
        ),
    ]
