# Generated by Django 5.2.11 on 2026-04-14 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_plan_tier_catalog_and_pricing_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_status', models.CharField(choices=[('closed', 'Closed'), ('suspended', 'Suspended'), ('active', 'Active')], max_length=20)),
                ('to_status', models.CharField(choices=[('closed', 'Closed'), ('suspended', 'Suspended'), ('active', 'Active')], max_length=20)),
                ('reason', models.CharField(choices=[('admin_decision', 'Admin Decision'), ('policy_violation', 'Policy Violation'), ('content_review', 'Content Review'), ('user_request', 'User Request'), ('technical_issue', 'Technical Issue'), ('other', 'Other')], default='admin_decision', max_length=50)),
                ('reason_text', models.TextField(blank=True, help_text='Detailed explanation for the status change')),
                ('changed_by', models.CharField(default='admin', help_text='User or system that performed the change', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='organization.announcement')),
            ],
            options={
                'ordering': ['-created_at', 'announcement_id'],
                'indexes': [models.Index(fields=['announcement', '-created_at'], name='organizatio_announc_605ad1_idx'), models.Index(fields=['to_status', '-created_at'], name='organizatio_to_stat_2528a4_idx')],
            },
        ),
    ]
