# Generated by Django 5.2.11 on 2026-09-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_organizationavailability'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationavailabilityexception',
            new_name='organizatio_setting_4f2c7a_idx',
            old_name='organizatio_setting_1c9f58_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationweeklyavailability',
            new_name='organizatio_setting_8949e9_idx',
            old_name='organizatio_setting_5b2506_idx',
        ),
    ]
