# Generated by Django 5.2.11 on 2026-09-30 21:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_rename_availability_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpricing',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US dollar'), ('GBP', 'Pound sterling')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='organizationpricing',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US dollar'), ('GBP', 'Pound sterling')], default='EUR', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='organizationpricing',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0)), name='organization_pricing_monthly_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='service_price_amount_not_negative'),
        ),
    ]
