# Generated by Django 5.2.11 on 2026-03-12 15:56

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_service_prices_to_subservices(apps, schema_editor):
    ServicePrice = apps.get_model("organization", "ServicePrice")
    Subservice = apps.get_model("organization", "Subservice")

    fallback_name = "Default priced subservice"
    service_to_subservice = {}

    for price in ServicePrice.objects.select_related("service").all():
        subservice = service_to_subservice.get(price.service_id)
        if subservice is None:
            subservice = (
                Subservice.objects.filter(service_id=price.service_id, name=fallback_name)
                .order_by("id")
                .first()
            )
            if subservice is None:
                subservice = Subservice.objects.create(
                    service_id=price.service_id,
                    name=fallback_name,
                    description="",
                )
            service_to_subservice[price.service_id] = subservice

        price.subservice_id = subservice.id
        price.save(update_fields=["subservice"])


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprice",
            name="subservice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_table",
                to="organization.subservice",
            ),
        ),
        migrations.RunPython(
            forwards_copy_service_prices_to_subservices,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="serviceprice",
            name="unique_service_price_effective_from",
        ),
        migrations.RemoveField(
            model_name="serviceprice",
            name="service",
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="subservice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_table",
                to="organization.subservice",
            ),
        ),
        migrations.AlterModelOptions(
            name="serviceprice",
            options={"ordering": ["subservice_id", "-effective_from", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="serviceprice",
            constraint=models.UniqueConstraint(
                fields=("subservice", "currency", "effective_from"),
                name="unique_subservice_price_effective_from",
            ),
        ),
    ]
