# Generated by Django 5.2.11 on 2026-03-18 00:00

import django.db.models.deletion
from django.db import migrations, models


def assign_default_category_to_services(apps, schema_editor):
    Category = apps.get_model("organization", "Category")
    Service = apps.get_model("organization", "Service")

    default_category, _ = Category.objects.get_or_create(
        name="General",
        defaults={"description": "Categoria por defecto para servicios migrados."},
    )
    Service.objects.filter(category__isnull=True).update(category=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_announcement_announcementreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="organization.category",
            ),
        ),
        migrations.AddField(
            model_name="serviceprice",
            name="charging_type",
            field=models.CharField(
                choices=[
                    ("per_day", "Per day"),
                    ("per_hour", "Per hour"),
                    ("per_square_meter", "Per square meter"),
                    ("per_project", "Per project"),
                ],
                default="per_project",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            assign_default_category_to_services,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="organization.category",
            ),
        ),
    ]
