# Generated by Django 5.2.11 on 2026-09-30 21:39

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def clear_out_of_range_ratings(apps, schema_editor):
    """Ratings outside 1-5 were accepted before; they carry no usable signal."""
    Job = apps.get_model("jobs", "Job")
    out_of_range = models.Q(organization_rating__lt=1) | models.Q(organization_rating__gt=5)
    Job.objects.filter(out_of_range).update(organization_rating=None)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('organization', '0017_rename_availability_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_out_of_range_ratings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='organization_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('organization_rating__isnull', True), models.Q(('organization_rating__gte', 1), ('organization_rating__lte', 5)), _connector='OR'), name='job_rating_between_1_and_5'),
        ),
    ]
