# Generated by Django 5.2.11 on 2026-03-13 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_move_chat_models_to_job_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='organization_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
