# Generated by Django 5.2.11 on 2026-03-11 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RgpdAnonymousConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_accepted', models.BooleanField(default=False)),
                ('cookies_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cookies_version', models.CharField(blank=True, max_length=64)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_version', models.CharField(blank=True, max_length=64)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('terms_and_conditions_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions_version', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('write_token_hash', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'RGPD anonymous consent',
                'verbose_name_plural': 'RGPD anonymous consents',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RgpdAnonymousConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('upsert', 'Upsert'), ('update', 'Update')], max_length=16)),
                ('cookies_accepted', models.BooleanField(default=False)),
                ('cookies_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cookies_version', models.CharField(blank=True, max_length=64)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_version', models.CharField(blank=True, max_length=64)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('terms_and_conditions_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions_version', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rgpd.rgpdanonymousconsent')),
            ],
            options={
                'verbose_name': 'RGPD anonymous consent event',
                'verbose_name_plural': 'RGPD anonymous consent events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RgpdConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_accepted', models.BooleanField(default=False)),
                ('cookies_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cookies_version', models.CharField(blank=True, max_length=64)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_version', models.CharField(blank=True, max_length=64)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('terms_and_conditions_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions_version', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rgpd_consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RGPD consent',
                'verbose_name_plural': 'RGPD consents',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RgpdConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('upsert', 'Upsert'), ('update', 'Update')], max_length=16)),
                ('cookies_accepted', models.BooleanField(default=False)),
                ('cookies_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cookies_version', models.CharField(blank=True, max_length=64)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_version', models.CharField(blank=True, max_length=64)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('terms_and_conditions_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions_version', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rgpd.rgpdconsent')),
            ],
            options={
                'verbose_name': 'RGPD consent event',
                'verbose_name_plural': 'RGPD consent events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
