"""
Django settings for Core project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"Environment variable {name} must be an integer.") from exc


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def require_env(name: str) -> str:
    value = os.getenv(name)
    if value:
        return value
    raise ImproperlyConfigured(f"Environment variable {name} is required.")


def read_project_version(default: str = "0.0.0") -> str:
    version_path = BASE_DIR / "VERSION"
    try:
        version = version_path.read_text(encoding="utf-8").strip()
    except OSError:
        return default
    return version or default


def enforce_production_bool(value: bool) -> bool:
    return True if IS_PRODUCTION else value


def disable_in_production_bool(value: bool) -> bool:
    return False if IS_PRODUCTION else value


def enforce_production_int(value: int, minimum: int) -> int:
    if not IS_PRODUCTION:
        return value
    return max(value, minimum)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
APP_MODE = os.getenv("APP_MODE", "development").strip().lower()
IS_PRODUCTION = APP_MODE == "production"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-unsafe-secret-key-change-me")
if IS_PRODUCTION and SECRET_KEY == "dev-only-unsafe-secret-key-change-me":
    raise ImproperlyConfigured(
        "SECRET_KEY must be configured via environment when APP_MODE=production."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=not IS_PRODUCTION)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS")
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be configured when APP_MODE=production.")

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
TRUSTED_PROXY_IPS = env_list("TRUSTED_PROXY_IPS")
CORS_ALLOW_ALL_ORIGINS = APP_MODE == "development"

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SECURE_HSTS_SECONDS = env_int(
    "SECURE_HSTS_SECONDS",
    default=31536000 if IS_PRODUCTION else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=IS_PRODUCTION,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=IS_PRODUCTION)

SECURE_SSL_REDIRECT = enforce_production_bool(SECURE_SSL_REDIRECT)
SECURE_HSTS_SECONDS = enforce_production_int(SECURE_HSTS_SECONDS, minimum=31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = enforce_production_bool(SECURE_HSTS_INCLUDE_SUBDOMAINS)
SECURE_HSTS_PRELOAD = enforce_production_bool(SECURE_HSTS_PRELOAD)
SESSION_COOKIE_SECURE = enforce_production_bool(SESSION_COOKIE_SECURE)
CSRF_COOKIE_SECURE = enforce_production_bool(CSRF_COOKIE_SECURE)

secure_proxy_ssl_header_raw = os.getenv(
    "SECURE_PROXY_SSL_HEADER",
    "HTTP_X_FORWARDED_PROTO,https" if IS_PRODUCTION else "",
).strip()
if secure_proxy_ssl_header_raw:
    secure_proxy_ssl_header_values = [
        value.strip() for value in secure_proxy_ssl_header_raw.split(",", 1)
    ]
    if len(secure_proxy_ssl_header_values) != 2 or not all(secure_proxy_ssl_header_values):
        raise ImproperlyConfigured(
            "SECURE_PROXY_SSL_HEADER must use format 'HEADER_NAME,header_value'."
        )
    SECURE_PROXY_SSL_HEADER = (
        secure_proxy_ssl_header_values[0],
        secure_proxy_ssl_header_values[1],
    )
else:
    SECURE_PROXY_SSL_HEADER = None

AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "test")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "test")
AWS_S3_ENDPOINT_URL = (
    os.getenv("AWS_S3_ENDPOINT_URL")
    or os.getenv("LOCALSTACK_ENDPOINT")
    or "http://localstack:4566"
)
AWS_SES_ENDPOINT_URL = os.getenv("AWS_SES_ENDPOINT_URL") or os.getenv("LOCALSTACK_ENDPOINT")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "bravo-media")
AWS_LEGAL_DOCUMENTS_BUCKET_NAME = os.getenv(
    "AWS_LEGAL_DOCUMENTS_BUCKET_NAME",
    f"{AWS_STORAGE_BUCKET_NAME}-legal",
)
AWS_S3_PUBLIC_URL = os.getenv("AWS_S3_PUBLIC_URL", "")
AWS_S3_PRESIGNED_URL_ENDPOINT = os.getenv("AWS_S3_PRESIGNED_URL_ENDPOINT", "")
MEDIA_PUBLIC_BASE_URL = os.getenv("MEDIA_PUBLIC_BASE_URL", "/s3")
LEGAL_DOCUMENTS_UPLOAD_PREFIX = os.getenv(
    "LEGAL_DOCUMENTS_UPLOAD_PREFIX",
    "legal-documents",
).strip().strip("/")
USE_S3_STORAGE = env_bool("USE_S3_STORAGE", default=True)
if not USE_S3_STORAGE:
    raise ImproperlyConfigured("USE_S3_STORAGE must remain enabled in this project.")
USE_SES_EMAIL = env_bool("USE_SES_EMAIL", default=bool(AWS_SES_ENDPOINT_URL))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@bravo.local")
LEGAL_DOCUMENT_MAX_BYTES = env_int("LEGAL_DOCUMENT_MAX_BYTES", 10 * 1024 * 1024)
LEGAL_DOCUMENT_ALLOWED_CONTENT_TYPES = env_list(
    "LEGAL_DOCUMENT_ALLOWED_CONTENT_TYPES",
    default=["application/pdf"],
)
JOB_CHAT_ATTACHMENT_MAX_BYTES = env_int("JOB_CHAT_ATTACHMENT_MAX_BYTES", 5 * 1024 * 1024)
JOB_CHAT_ATTACHMENT_URL_TTL_SECONDS = env_int("JOB_CHAT_ATTACHMENT_URL_TTL_SECONDS", 300)
JOB_CHAT_ATTACHMENT_ALLOWED_CONTENT_TYPES = env_list(
    "JOB_CHAT_ATTACHMENT_ALLOWED_CONTENT_TYPES",
    default=["application/pdf", "image/jpeg", "image/png", "text/plain"],
)
ORGANIZATION_ANNOUNCEMENT_IMAGE_MAX_BYTES = env_int(
    "ORGANIZATION_ANNOUNCEMENT_IMAGE_MAX_BYTES", 5 * 1024 * 1024
)
ORGANIZATION_ANNOUNCEMENT_IMAGE_UPLOAD_URL_TTL_SECONDS = env_int(
    "ORGANIZATION_ANNOUNCEMENT_IMAGE_UPLOAD_URL_TTL_SECONDS", 300
)
ORGANIZATION_ANNOUNCEMENT_IMAGE_PENDING_MAX_AGE_SECONDS = env_int(
    "ORGANIZATION_ANNOUNCEMENT_IMAGE_PENDING_MAX_AGE_SECONDS", 3600
)
ORGANIZATION_ANNOUNCEMENT_IMAGE_ALLOWED_CONTENT_TYPES = env_list(
    "ORGANIZATION_ANNOUNCEMENT_IMAGE_ALLOWED_CONTENT_TYPES",
    default=["image/jpeg", "image/png"],
)
ORGANIZATION_ANNOUNCEMENT_VIEW_TTL_SECONDS = env_int(
    "ORGANIZATION_ANNOUNCEMENT_VIEW_TTL_SECONDS",
    60 * 60 * 24 * 30,
)
JOB_CHAT_WS_RATE_LIMIT = env_int("JOB_CHAT_WS_RATE_LIMIT", 20)
JOB_CHAT_WS_RATE_WINDOW = env_int("JOB_CHAT_WS_RATE_WINDOW", 60)
AUTH_VERIFY_EMAIL_URL_TEMPLATE = os.getenv(
    "AUTH_VERIFY_EMAIL_URL_TEMPLATE",
    "http://localhost:3000/verify-email?token={token}",
)
AUTH_VERIFY_EMAIL_SALT = os.getenv(
    "AUTH_VERIFY_EMAIL_SALT",
    "auth.verify_email",
)
AUTH_VERIFY_EMAIL_MAX_AGE_SECONDS = env_int(
    "AUTH_VERIFY_EMAIL_MAX_AGE_SECONDS",
    60 * 60 * 24,
)
AUTH_BYPASS_EMAIL_VERIFICATION = env_bool(
    "AUTH_BYPASS_EMAIL_VERIFICATION",
    default=not IS_PRODUCTION,
)
BYPASS_ADMIN_LOGIN = env_bool(
    "BYPASS_ADMIN_LOGIN",
    default=False,
)
BYPASS_ORGANIZATION_VALIDATION = env_bool(
    "BYPASS_ORGANIZATION_VALIDATION",
    default=False,
)
AUTH_ENFORCE_PASSWORD_RESTRICTIONS = env_bool(
    "AUTH_ENFORCE_PASSWORD_RESTRICTIONS",
    default=True,
)
HIDE_API_DOCS = env_bool(
    "HIDE_API_DOCS",
    default=IS_PRODUCTION,
)
RGPD_MODULE_ENABLED = env_bool("RGPD_MODULE_ENABLED", default=False)
LEGAL_DOCUMENTS_ROOT = Path(
    os.getenv("LEGAL_DOCUMENTS_ROOT", str(BASE_DIR / "docs"))
).resolve()

AUTH_BYPASS_EMAIL_VERIFICATION = disable_in_production_bool(AUTH_BYPASS_EMAIL_VERIFICATION)
BYPASS_ADMIN_LOGIN = disable_in_production_bool(BYPASS_ADMIN_LOGIN)
BYPASS_ORGANIZATION_VALIDATION = disable_in_production_bool(BYPASS_ORGANIZATION_VALIDATION)

if IS_PRODUCTION and USE_S3_STORAGE:
    require_env("AWS_DEFAULT_REGION")
    require_env("AWS_ACCESS_KEY_ID")
    require_env("AWS_SECRET_ACCESS_KEY")
    require_env("AWS_STORAGE_BUCKET_NAME")
    require_env("AWS_LEGAL_DOCUMENTS_BUCKET_NAME")

if IS_PRODUCTION and USE_SES_EMAIL:
    require_env("DEFAULT_FROM_EMAIL")
    require_env("AWS_DEFAULT_REGION")
    require_env("AWS_ACCESS_KEY_ID")
    require_env("AWS_SECRET_ACCESS_KEY")


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'django_extensions',
    'channels',
    'apps.auth.apps.AuthConfig',
    'apps.organization.apps.OrganizationConfig',
    'apps.management.apps.ManagementConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.jobs.apps.JobsConfig',
    'apps.job_chat.apps.JobChatConfig',
    'apps.assets.apps.AssetsConfig',
    'apps.statistics.apps.StatisticsConfig',
]

if RGPD_MODULE_ENABLED:
    INSTALLED_APPS.append('apps.rgpd.apps.RgpdConfig')

if USE_S3_STORAGE:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.organization.middleware.AnnouncementViewCountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Core.wsgi.application'
ASGI_APPLICATION = 'Core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_url = os.getenv("DATABASE_URL")
if IS_PRODUCTION and not database_url:
    require_env("DATABASE_URL")

if database_url:
    parsed_db = urlparse(database_url)
    if parsed_db.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured("DATABASE_URL must use postgres/postgresql scheme.")
    if not parsed_db.path.lstrip("/") or not parsed_db.hostname:
        raise ImproperlyConfigured("DATABASE_URL must include host and database name.")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed_db.path.lstrip("/"),
            "USER": parsed_db.username,
            "PASSWORD": parsed_db.password,
            "HOST": parsed_db.hostname,
            "PORT": parsed_db.port or 5432,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = (
    [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]
    if AUTH_ENFORCE_PASSWORD_RESTRICTIONS
    else []
)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

if USE_S3_STORAGE:
    AWS_S3_REGION_NAME = AWS_DEFAULT_REGION
    AWS_S3_ADDRESSING_STYLE = "path"
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "legal_documents": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_LEGAL_DOCUMENTS_BUCKET_NAME,
                "default_acl": None,
                "file_overwrite": False,
                "querystring_auth": True,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }
    if MEDIA_PUBLIC_BASE_URL:
        MEDIA_URL = f"{MEDIA_PUBLIC_BASE_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
    elif AWS_S3_PUBLIC_URL:
        MEDIA_URL = f"{AWS_S3_PUBLIC_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
    elif AWS_S3_ENDPOINT_URL:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
else:
    MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'custom_auth.CustomUser'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "common.pagination.DefaultPageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth_default": os.getenv("AUTH_DEFAULT_THROTTLE_RATE", "60/minute"),
        "auth_login": os.getenv("AUTH_LOGIN_THROTTLE_RATE", "5/minute"),
        "auth_register": os.getenv("AUTH_REGISTER_THROTTLE_RATE", "3/minute"),
        "auth_refresh": os.getenv("AUTH_REFRESH_THROTTLE_RATE", "10/minute"),
        "auth_verify_email": os.getenv("AUTH_VERIFY_EMAIL_THROTTLE_RATE", "10/minute"),
        "organization_default": os.getenv("ORGANIZATION_DEFAULT_THROTTLE_RATE", "60/minute"),
        "organization_public_read": os.getenv("ORGANIZATION_PUBLIC_READ_THROTTLE_RATE", "60/minute"),
        "organization_authenticated_read": os.getenv(
            "ORGANIZATION_AUTHENTICATED_READ_THROTTLE_RATE",
            "120/minute",
        ),
        "organization_write": os.getenv("ORGANIZATION_WRITE_THROTTLE_RATE", "30/minute"),
        "organization_admin": os.getenv("ORGANIZATION_ADMIN_THROTTLE_RATE", "30/minute"),
        "rgpd_authenticated_read": os.getenv("RGPD_AUTHENTICATED_READ_THROTTLE_RATE", "120/minute"),
        "rgpd_authenticated_write": os.getenv("RGPD_AUTHENTICATED_WRITE_THROTTLE_RATE", "30/minute"),
        "rgpd_anonymous_write": os.getenv("RGPD_ANONYMOUS_WRITE_THROTTLE_RATE", "20/minute"),
        "management_default": os.getenv("MANAGEMENT_DEFAULT_THROTTLE_RATE", "30/minute"),
        "management_read": os.getenv("MANAGEMENT_READ_THROTTLE_RATE", "60/minute"),
        "management_write": os.getenv("MANAGEMENT_WRITE_THROTTLE_RATE", "20/minute"),
        "management_status": os.getenv("MANAGEMENT_STATUS_THROTTLE_RATE", "10/minute"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": env_bool("JWT_ROTATE_REFRESH_TOKENS", default=True),
}

spectacular_enum_name_overrides = {
    "ActiveStateStatusEnum": "apps.auth.models.CustomUser.Status",
    "AnnouncementStatusEnum": "apps.organization.models.announcement.Announcement.Status",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Bravo API",
    "DESCRIPTION": "OpenAPI documentation for the Bravo backend.",
    "VERSION": read_project_version(),
    "TAGS": [
        {"name": "Auth"},
        {"name": "Catalog"},
        {"name": "Announcements"},
        {"name": "Organizations"},
        {"name": "Services"},
        {"name": "Management / Users"},
        {"name": "Management / Organizations"},
        {"name": "Management / Jobs"},
        {"name": "Management / Feature Flags"},
        {"name": "Management / Categories"},
        {"name": "Management / Allowed Cities"},
        {"name": "RGPD"},
    ],
    "ENUM_NAME_OVERRIDES": spectacular_enum_name_overrides,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "operationsSorter": "alpha",
    },
}

redis_url = os.getenv("REDIS_URL")
if IS_PRODUCTION and not redis_url:
    require_env("REDIS_URL")

if redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [redis_url],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

default_email_backend = (
    "common.email_backends.SesEmailBackend"
    if USE_SES_EMAIL
    else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", default_email_backend).strip() or default_email_backend
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = env_int("EMAIL_PORT", 25)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=False)
