# Generated by Django 5.2.11 on 2026-05-04 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


INITIAL_POLICY_CONTENT = {
    "privacy_policy": {
        "title": "Politica de privacidad",
        "body_markdown": (
            "Informacion que recopilamos\n\n"
            "Recopilamos los datos necesarios para crear tu cuenta, prestar el servicio, "
            "gestionar comunicaciones, prevenir fraude y cumplir obligaciones legales.\n\n"
            "Como usamos tu informacion\n\n"
            "Usamos tus datos para operar la plataforma, mejorar el servicio, atender solicitudes, "
            "procesar transacciones y mantener la seguridad.\n\n"
            "Tus derechos\n\n"
            "Puedes solicitar acceso, rectificacion, supresion, portabilidad, limitacion y oposicion "
            "desde la app o contactando con soporte.\n"
        ),
    },
    "terms_and_conditions": {
        "title": "Terminos y condiciones",
        "body_markdown": (
            "Aceptacion de terminos\n\n"
            "Al crear una cuenta o usar Bravo aceptas estos terminos y condiciones.\n\n"
            "Uso permitido\n\n"
            "Debes usar la plataforma de forma legal, sin fraude, sin acceso no autorizado y "
            "sin perjudicar a otros usuarios.\n\n"
            "Cuentas y responsabilidad\n\n"
            "Eres responsable de la actividad realizada con tu cuenta y de mantener seguras tus credenciales.\n"
        ),
    },
    "cookies_policy": {
        "title": "Politica de cookies",
        "body_markdown": (
            "Que son las cookies\n\n"
            "Las cookies son pequeños archivos que permiten recordar preferencias y medir el uso de la plataforma.\n\n"
            "Tipos de cookies\n\n"
            "Usamos cookies esenciales para autenticacion y seguridad, y solo activaremos cookies no esenciales "
            "cuando exista consentimiento.\n\n"
            "Control de cookies\n\n"
            "Puedes revisar y actualizar tus preferencias de cookies desde la aplicacion.\n"
        ),
    },
}


def seed_policy_documents(apps, schema_editor):
    RgpdPolicyDocument = apps.get_model("rgpd", "RgpdPolicyDocument")
    RgpdPolicyVersion = apps.get_model("rgpd", "RgpdPolicyVersion")
    now = django.utils.timezone.now()

    for document_type, payload in INITIAL_POLICY_CONTENT.items():
        document, _ = RgpdPolicyDocument.objects.get_or_create(document_type=document_type)
        RgpdPolicyVersion.objects.get_or_create(
            document=document,
            version="2026-05",
            defaults={
                "title": payload["title"],
                "body_markdown": payload["body_markdown"],
                "is_published": True,
                "is_current": True,
                "published_at": now,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rgpd", "0002_rgpdlegaldocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="RgpdDataRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("request_type", models.CharField(choices=[("access", "Access"), ("rectification", "Rectification"), ("erasure", "Erasure"), ("portability", "Portability"), ("restriction", "Restriction"), ("objection", "Objection")], max_length=32)),
                ("status", models.CharField(choices=[("submitted", "Submitted"), ("in_review", "In review"), ("completed", "Completed"), ("rejected", "Rejected")], default="submitted", max_length=32)),
                ("details", models.TextField(blank=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_rgpd_data_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rgpd_data_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "RGPD data request",
                "verbose_name_plural": "RGPD data requests",
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RgpdPolicyDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("document_type", models.CharField(choices=[("privacy_policy", "Privacy policy"), ("terms_and_conditions", "Terms and conditions"), ("cookies_policy", "Cookies policy")], max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RGPD policy document",
                "verbose_name_plural": "RGPD policy documents",
                "ordering": ["document_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="RgpdPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("body_markdown", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="rgpd.rgpdpolicydocument")),
            ],
            options={
                "verbose_name": "RGPD policy version",
                "verbose_name_plural": "RGPD policy versions",
                "ordering": ["document__document_type", "-published_at", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RgpdPolicyAcceptance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("anonymous_consent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="policy_acceptances", to="rgpd.rgpdanonymousconsent")),
                ("policy_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="acceptances", to="rgpd.rgpdpolicyversion")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="rgpd_policy_acceptances", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "RGPD policy acceptance",
                "verbose_name_plural": "RGPD policy acceptances",
                "ordering": ["-accepted_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="rgpdpolicyversion",
            constraint=models.UniqueConstraint(fields=("document", "version"), name="rgpd_unique_policy_version_per_document"),
        ),
        migrations.AddConstraint(
            model_name="rgpdpolicyversion",
            constraint=models.UniqueConstraint(condition=models.Q(("is_current", True)), fields=("document",), name="rgpd_single_current_policy_version_per_document"),
        ),
        migrations.AddConstraint(
            model_name="rgpdpolicyacceptance",
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(user__isnull=False) & models.Q(anonymous_consent__isnull=True))
                    | (models.Q(user__isnull=True) & models.Q(anonymous_consent__isnull=False))
                ),
                name="rgpd_policy_acceptance_requires_single_subject",
            ),
        ),
        migrations.RunPython(seed_policy_documents, migrations.RunPython.noop),
    ]
