# Generated by Django 5.2.11 on 2026-04-15 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='jobs.job')),
            ],
            options={
                'db_table': 'job_chat_jobchat',
            },
        ),
        migrations.CreateModel(
            name='JobChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='job_chat.jobchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_chat_jobchatmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobChatAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file', models.FileField(upload_to='job_chat_attachments/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='job_chat.jobchatmessage')),
            ],
            options={
                'db_table': 'job_chat_jobchatattachment',
            },
        ),
        migrations.AddIndex(
            model_name='jobchat',
            index=models.Index(fields=['-created_at'], name='job_chat_jo_created_d4afe9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobchat',
            index=models.Index(fields=['job'], name='job_chat_jo_job_id_73e3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobchatmessage',
            index=models.Index(fields=['job_chat', '-created_at'], name='job_chat_jo_job_cha_9611b7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobchatmessage',
            index=models.Index(fields=['user', '-created_at'], name='job_chat_jo_user_id_361459_idx'),
        ),
        migrations.AddIndex(
            model_name='jobchatattachment',
            index=models.Index(fields=['message'], name='job_chat_jo_message_ba403e_idx'),
        ),
    ]
