# Generated by Django 5.2.11 on 2026-04-16 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')], max_length=20)),
                ('kind', models.CharField(choices=[('announcement_image', 'Announcement image'), ('job_chat_attachment', 'Job chat attachment'), ('legal_document', 'Legal document'), ('generic_upload', 'Generic upload')], max_length=40)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploaded', 'Uploaded'), ('confirmed', 'Confirmed'), ('attached', 'Attached'), ('orphan', 'Orphan'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='initiated', max_length=20)),
                ('pending_key', models.CharField(blank=True, max_length=1024)),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type_client', models.CharField(blank=True, max_length=120)),
                ('size_client', models.BigIntegerField(blank=True, null=True)),
                ('content_type_detected', models.CharField(blank=True, max_length=120)),
                ('size_actual', models.BigIntegerField(blank=True, null=True)),
                ('is_temporary', models.BooleanField(default=True)),
                ('draft_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_asset',
                'indexes': [models.Index(fields=['owner', 'status'], name='assets_asse_owner_i_6f51c8_idx'), models.Index(fields=['kind', 'status'], name='assets_asse_kind_0c48fe_idx'), models.Index(fields=['expires_at'], name='assets_asse_expires_fc725b_idx')],
            },
        ),
    ]
