# Generated by Django 5.2.11 on 2026-09-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_origin_62e718_idx',
            old_name='notifications_origin_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_categor_6dc2ff_idx',
            old_name='notifications_category_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_target__3d7466_idx',
            old_name='notifications_target_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdispatch',
            new_name='notificatio_channel_34e896_idx',
            old_name='notifications_dispatch_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdispatch',
            new_name='notificatio_status_e96bb9_idx',
            old_name='notifications_dispatch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecipient',
            new_name='notificatio_user_id_b9cd65_idx',
            old_name='notifications_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecipient',
            new_name='notificatio_notific_3bb616_idx',
            old_name='notifications_notification_user_idx',
        ),
    ]
